export const RETRIEVE_PRODUTOS = "RETRIEVE_PRODUTOS";
export const ACCESS_DATA = "ACCESS_DATA";
export const ALL_PRODUCTS = "ALL_PRODUCTS";
export const ACCESS_ABSOLUTE_VALUES_PRODUCTS = "ACCESS_ABSOLUTE_VALUES_PRODUCTS";